#!/bin/bash
# init-env.sh - Initialize .env with smart defaults from local git config
set -e

echo "🔧 Initializing .env configuration..."
echo ""

# Check if .env already exists
if [ -f .env ]; then
    read -p "⚠️  .env already exists. Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 0
    fi
fi

# Get git config from local machine
GIT_NAME=$(git config --global user.name 2>/dev/null || echo "")
GIT_EMAIL=$(git config --global user.email 2>/dev/null || echo "")

# Try to get GitHub username from git config or gh CLI
GITHUB_USER=""
if command -v gh &> /dev/null; then
    GITHUB_USER=$(gh api user --jq .login 2>/dev/null || echo "")
fi
if [ -z "$GITHUB_USER" ]; then
    # Try to extract from git remote
    GITHUB_USER=$(git config --global github.user 2>/dev/null || echo "")
fi

# Default values
TF_NETWORK="main"
AI_NODE=""
CPU="4"
MEM="8192"
DISK="100"
CONNECTIVITY="wireguard"

# Prompt for TFGrid node (required)
echo "📡 ThreeFold Grid Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
read -p "Node ID for AI Agent VM: " AI_NODE
if [ -z "$AI_NODE" ]; then
    echo "❌ Error: Node ID is required"
    exit 1
fi

# Prompt for network if not main
read -p "TFGrid Network (main/test/dev) [main]: " NETWORK_INPUT
TF_NETWORK=${NETWORK_INPUT:-main}

echo ""
echo "🔧 VM Resources"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
read -p "CPU cores [4]: " CPU_INPUT
CPU=${CPU_INPUT:-4}
read -p "Memory (MB) [8192]: " MEM_INPUT
MEM=${MEM_INPUT:-8192}
read -p "Disk (GB) [100]: " DISK_INPUT
DISK=${DISK_INPUT:-100}

echo ""
echo "🌐 Network Connectivity"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
read -p "Connectivity network (wireguard/mycelium) [wireguard]: " CONN_INPUT
CONNECTIVITY=${CONN_INPUT:-wireguard}

# Git configuration
echo ""
echo "🔐 Git Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if [ -n "$GIT_NAME" ]; then
    echo "✅ Found local git config:"
    echo "   Name:  $GIT_NAME"
    echo "   Email: $GIT_EMAIL"
    read -p "Use this config? (Y/n): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Nn]$ ]]; then
        read -p "Enter git name: " GIT_NAME
        read -p "Enter git email: " GIT_EMAIL
    fi
else
    echo "⚠️  No local git config found"
    read -p "Enter git name: " GIT_NAME
    read -p "Enter git email: " GIT_EMAIL
fi

# GitHub username
if [ -n "$GITHUB_USER" ]; then
    echo ""
    read -p "GitHub username [$GITHUB_USER]: " GH_INPUT
    GITHUB_USER=${GH_INPUT:-$GITHUB_USER}
else
    read -p "GitHub username (optional): " GITHUB_USER
fi

# Create .env file
cat > .env <<EOF
# TFGrid AI-Agent Configuration
# Generated by init-env.sh on $(date)
# Edit this file to customize your deployment

# ==============================================================================
# THREEFOLD GRID CONFIGURATION
# ==============================================================================

# Network: main, test, or dev
export TF_VAR_tfgrid_network="$TF_NETWORK"

# Node ID for AI Agent VM
export TF_VAR_ai_agent_node=$AI_NODE

# VM Resources
export TF_VAR_ai_agent_cpu=$CPU
export TF_VAR_ai_agent_mem=$MEM
export TF_VAR_ai_agent_disk=$DISK

# ==============================================================================
# NETWORK CONFIGURATION
# ==============================================================================

# Connectivity network: wireguard or mycelium
export CONNECTIVITY_NETWORK="$CONNECTIVITY"

# ==============================================================================
# GIT CONFIGURATION
# ==============================================================================

# Git Identity (for commits made by AI agent)
export GIT_USER_NAME="$GIT_NAME"
export GIT_USER_EMAIL="$GIT_EMAIL"
EOF

# Add optional GitHub config if provided
if [ -n "$GITHUB_USER" ]; then
    cat >> .env <<EOF

# Git Providers (optional)
export GITHUB_USER="$GITHUB_USER"
EOF
fi

cat >> .env <<EOF

# ==============================================================================
# NOTES
# ==============================================================================
# Sensitive data (mnemonic, API keys) should NOT be in this file.
# Set them as environment variables:
#   set -x TF_VAR_mnemonic (cat ~/.config/threefold/mnemonic)
#   set -x ANTHROPIC_API_KEY "your-api-key"  # Optional for Claude
EOF

echo ""
echo "✅ Configuration saved to .env"
echo ""
echo "📋 Review your configuration:"
cat .env | grep "^export" | sed 's/export /  /'
echo ""
echo "Next steps:"
echo "  1. Set your TFGrid mnemonic (required):"
echo "     set -x TF_VAR_mnemonic (cat ~/.config/threefold/mnemonic)"
echo ""
echo "  2. Set GitHub token (optional - for automated git push from VM):"
echo "     set -x GITHUB_TOKEN (cat ~/.config/threefold/github_token)"
echo ""
echo "  3. Deploy: make deploy"
echo ""
echo "ℹ️  Note: Without GitHub token, you'll add VM's SSH key to GitHub manually"
echo ""
